// auth reducer types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS';
export const SET_PROFILE_FAIL = 'SET_PROFILE_FAIL';
export const SET_AUTH_PROFILE_SUCCESS = 'SET_AUTH_PROFILE_SUCCESS';
export const SET_AUTH_PROFILE_FAIL = 'SET_AUTH_PROFILE_FAIL';
export const UNSET_PROFILE = 'UNSET_PROFILE';
export const LOADING_AUTH = 'LOADING_AUTH';

// ui reducer types
export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';
export const LOADING_UI = 'LOADING_UI';

// fleet data reducer types
export const SET_FLEETS_SUCCESS = 'SET_FLEETS_SUCCESS';
export const SET_FLEETS_FAIL = 'SET_FLEETS_FAIL';
export const SET_FLEET_SUCCESS = 'SET_FLEET_SUCCESS';
export const SET_FLEET_FAIL = 'SET_FLEET_FAIL';
export const UNSET_FLEET = 'UNSET_FLEET';
export const CREATE_FLEET_POST_SUCCESS = 'CREATE_FLEET_POST_SUCCESS';
export const CREATE_FLEET_POST_FAIL = 'CREATE_FLEET_POST_FAIL';
export const UPDATE_FLEET_POST_SUCCESS = 'UPDATE_FLEET_POST_SUCCESS';
export const UPDATE_FLEET_POST_FAIL = 'UPDATE_FLEET_POST_FAIL';
export const DELETE_FLEET_POST_SUCCESS = 'DELETE_FLEET_POST_SUCCESS';
export const DELETE_FLEET_POST_FAIL = 'DELETE_FLEET_POST_FAIL';
export const LOADING_FLEET = 'LOADING_FLEET';
